name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.14
  - pip:
    - ipywidgets==8.1.2
    - hydra-core==1.3.2
    - jupyterlab==4.2.0
    - matplotlib==3.8.2
    - mlflow==2.8.1
    - pandas==2.1.3
    - scikit-learn==1.3.2
    - wandb==0.17.0
    - ydata-profiling==4.8.3
