name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.14
  - pip:
    - mlflow==2.12.2
    - pandas==2.1.3
    - pytest==8.2.0
    - scipy==1.13.0
    - wandb==0.17.0
