name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.14
  - pip:
    - hydra-core==1.3.2
    - jupyterlab==4.0.9
    - matplotlib==3.8.2
    - mlflow==2.12.2
    - pandas==2.1.3
    - wandb==0.17.0
