name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.14
  - pip:
    - mlflow==2.12.2
    - pandas==2.1.3
    - requests==2.24.0
    - scikit-learn==1.3.2
    - wandb==0.17.0
    - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
